spring:
  application:
    name:
      news-recommendation-service
logging:
  level:
    org.hsse.news.api: DEBUG
    org.hsse.news.database: DEBUG
tg-bot:
  token: 7838862242:AAE6mOjuLuuWAVzc46oMsZKVkJ1reTsjbzM