spring:
  application:
    name:
      news-recommendation-service
  datasource:
    url: jdbc:postgresql://localhost:5432/nrs
    username: nrs
    password: nrs-password
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgresSQLDialect
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
logging:
  level:
    org.hsse.news.api: DEBUG
    org.hsse.news.database: DEBUG
    org.hsse.news: DEBUG
tg-bot:
  token: token
