spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: email
    password: app-password
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  application:
    name:
      news-recommendation-service
  datasource:
    url: jdbc:postgresql://localhost:5432/nrs
    username: nrs
    password: nrs-password
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgresSQLDialect
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
logging:
  level:
    org.hsse.news.api: DEBUG
    org.hsse.news.database: DEBUG
    org.hsse.news.tracker: DEBUG
    org.hsse.news: DEBUG
tg-bot:
  token: 7784722859:AAFTJghjJI8nyH-pyNMBzzltnTysT5_T8W4
